using Microsoft.EntityFrameworkCore;

namespace CloudDentalOffice.Portal.Data;

/// <summary>
/// Adds the clearinghouse connection table to PostgreSQL databases provisioned
/// with EnsureCreated before it existed (EnsureCreated never adds tables to an
/// existing database). Mirrors the AddTenantClearinghouseConnections migration.
/// </summary>
public static class ClearinghouseConnectionSchemaReconciliation
{
    public static async Task ApplyAsync(
        CloudDentalDbContext dbContext,
        string databaseProvider,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (!string.Equals(databaseProvider, "PostgreSQL", StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        const string sql = """
            CREATE TABLE IF NOT EXISTS "TenantClearinghouseConnections" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "TenantId" character varying(64) NOT NULL,
                "Provider" character varying(32) NOT NULL,
                "Mode" character varying(24) NOT NULL,
                "Status" character varying(24) NOT NULL,
                "StediAccountId" character varying(100),
                "KeyReference" character varying(127),
                "EligibilityGateway" character varying(32) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL,
                "RotatedAt" timestamp with time zone,
                CONSTRAINT "PK_TenantClearinghouseConnections" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_TenantClearinghouseConnections_TenantId_Provider"
                ON "TenantClearinghouseConnections" ("TenantId", "Provider");
            """;

        await dbContext.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        logger.LogInformation("Clearinghouse connection schema reconciliation completed");
    }
}
