using Microsoft.EntityFrameworkCore;

namespace CloudDentalOffice.Portal.Data;

/// <summary>
/// Adds the per-appointment coverage verification table, and the coverage's
/// check lease, to PostgreSQL databases provisioned with EnsureCreated before
/// they existed. Mirrors the
/// AddCoverageVerifications migration; column types and names match what Npgsql
/// generates for the current model.
/// </summary>
public static class CoverageVerificationSchemaReconciliation
{
    public static async Task ApplyAsync(
        CloudDentalDbContext dbContext,
        string databaseProvider,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (!string.Equals(databaseProvider, "PostgreSQL", StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        const string sql = """
            ALTER TABLE "PatientInsurances" ADD COLUMN IF NOT EXISTS "VerificationLockedUntil" timestamp with time zone;

            CREATE TABLE IF NOT EXISTS "CoverageVerifications" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                "TenantId" character varying(64) NOT NULL,
                "AppointmentId" uuid NOT NULL,
                "PatientId" integer NOT NULL,
                "ProviderId" integer NOT NULL,
                "AppointmentStart" timestamp with time zone NOT NULL,
                "PatientInsuranceId" integer,
                "State" character varying(24),
                "Reason" character varying(500),
                "LastCheckedAt" timestamp with time zone,
                "Attempts" integer NOT NULL,
                "NextCheckAt" timestamp with time zone,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL,
                "ClosedAt" timestamp with time zone,
                CONSTRAINT "PK_CoverageVerifications" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_CoverageVerifications_TenantId_AppointmentId"
                ON "CoverageVerifications" ("TenantId", "AppointmentId");
            CREATE INDEX IF NOT EXISTS "IX_CoverageVerifications_TenantId_ClosedAt_AppointmentStart"
                ON "CoverageVerifications" ("TenantId", "ClosedAt", "AppointmentStart");
            """;

        await dbContext.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        logger.LogInformation("Coverage verification schema reconciliation completed");
    }
}
