using Microsoft.EntityFrameworkCore;

namespace CloudDentalOffice.Portal.Data;

/// <summary>
/// Adds eligibility check history to PostgreSQL databases provisioned with
/// EnsureCreated before it existed (EnsureCreated never alters an existing
/// database). Mirrors the AddEligibilityVerifications migration; column types
/// and names match what Npgsql generates for the current model.
/// </summary>
public static class EligibilityVerificationSchemaReconciliation
{
    public static async Task ApplyAsync(
        CloudDentalDbContext dbContext,
        string databaseProvider,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (!string.Equals(databaseProvider, "PostgreSQL", StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        const string sql = """
            ALTER TABLE "PatientInsurances" ADD COLUMN IF NOT EXISTS "LastVerifiedAt" timestamp with time zone;
            ALTER TABLE "PatientInsurances" ADD COLUMN IF NOT EXISTS "LastVerificationState" character varying(24);

            CREATE TABLE IF NOT EXISTS "EligibilityVerifications" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                "TenantId" character varying(64) NOT NULL,
                "PatientInsuranceId" integer NOT NULL,
                "PatientId" integer NOT NULL,
                "ServiceDate" date NOT NULL,
                "State" character varying(24) NOT NULL,
                "Reason" character varying(500),
                "CorrelationId" character varying(64),
                "Source" character varying(64),
                "CheckedAt" timestamp with time zone NOT NULL,
                "ResultJson" text,
                CONSTRAINT "PK_EligibilityVerifications" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_EligibilityVerifications_PatientInsurances_PatientInsurance~" FOREIGN KEY ("PatientInsuranceId")
                    REFERENCES "PatientInsurances" ("PatientInsuranceId") ON DELETE CASCADE
            );

            CREATE INDEX IF NOT EXISTS "IX_EligibilityVerifications_PatientInsuranceId"
                ON "EligibilityVerifications" ("PatientInsuranceId");
            CREATE INDEX IF NOT EXISTS "IX_EligibilityVerifications_TenantId_PatientInsuranceId_Checke~"
                ON "EligibilityVerifications" ("TenantId", "PatientInsuranceId", "CheckedAt");
            """;

        await dbContext.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        logger.LogInformation("Eligibility verification schema reconciliation completed");
    }
}
