using Microsoft.EntityFrameworkCore;

namespace CloudDentalOffice.Portal.Data;

/// <summary>
/// Adds the review-outreach tables to production databases that were originally
/// provisioned with EnsureCreated before the feature existed. EnsureCreated is
/// intentionally retained for the legacy PostgreSQL schema, but it never adds
/// newly introduced tables to an existing database.
/// </summary>
public static class ReviewOutreachSchemaReconciliation
{
    public static async Task ApplyAsync(
        CloudDentalDbContext dbContext,
        string databaseProvider,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (!string.Equals(databaseProvider, "PostgreSQL", StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        const string sql = """
            CREATE TABLE IF NOT EXISTS "ReviewOutreachSettings" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "TenantId" character varying(64) NOT NULL DEFAULT 'demo',
                "Enabled" boolean NOT NULL,
                "DelayMinutes" integer NOT NULL,
                "ReviewLandingPageUrl" character varying(2048),
                "GoogleReviewUrl" character varying(2048),
                "SenderName" character varying(120) NOT NULL,
                CONSTRAINT "PK_ReviewOutreachSettings" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ReviewOutreachSettings_TenantId"
                ON "ReviewOutreachSettings" ("TenantId");

            CREATE TABLE IF NOT EXISTS "ReviewOutreaches" (
                "Id" uuid NOT NULL,
                "TenantId" character varying(64) NOT NULL DEFAULT 'demo',
                "AppointmentId" uuid NOT NULL,
                "PatientId" integer NOT NULL,
                "RecipientEmail" character varying(320) NOT NULL,
                "Campaign" character varying(40) NOT NULL,
                "Channel" integer NOT NULL,
                "Status" integer NOT NULL,
                "ScheduledAt" timestamp with time zone NOT NULL,
                "SentAt" timestamp with time zone,
                "AttemptCount" integer NOT NULL,
                "LastAttemptAt" timestamp with time zone,
                "NextAttemptAt" timestamp with time zone,
                "FailureReason" character varying(128),
                "LockId" uuid,
                "LockedUntil" timestamp with time zone,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_ReviewOutreaches" PRIMARY KEY ("Id")
            );

            CREATE INDEX IF NOT EXISTS "IX_ReviewOutreaches_Status_ScheduledAt_NextAttemptAt"
                ON "ReviewOutreaches" ("Status", "ScheduledAt", "NextAttemptAt");

            CREATE INDEX IF NOT EXISTS "IX_ReviewOutreaches_TenantId"
                ON "ReviewOutreaches" ("TenantId");

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ReviewOutreaches_TenantId_AppointmentId_Campaign"
                ON "ReviewOutreaches" ("TenantId", "AppointmentId", "Campaign");
            """;

        await dbContext.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        logger.LogInformation("Review outreach schema reconciliation completed");
    }
}
