apiVersion: v1
kind: Secret
metadata:
  name: cdo-app-secrets
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=postgres;Database=cdo_portal;Username=cdo;Password=cdo_dev_password
  ConnectionStrings__PatientDb: Host=postgres;Database=cdo_patients;Username=cdo;Password=cdo_dev_password
  ConnectionStrings__SchedulingDb: Host=postgres;Database=cdo_scheduling;Username=cdo;Password=cdo_dev_password
  ConnectionStrings__ClaimsDb: Host=postgres;Database=cdo_claims;Username=cdo;Password=cdo_dev_password
  ConnectionStrings__PrescriptionDb: Host=postgres;Database=cdo_prescriptions;Username=cdo;Password=cdo_dev_password
  ConnectionStrings__VisionDb: Host=postgres;Database=cdo_vision;Username=cdo;Password=cdo_dev_password
  Jwt__Key: LocalDevelopmentOnly_CloudDentalOffice_Key_ChangeBeforeProduction_12345
  Jwt__Issuer: CloudDentalOffice
  Jwt__Audience: CloudDentalOffice
